### ISSUE TITLE
The memory and CPU usage are different from those shown in the task m

### ISSUE THREAD

**Issue by freebacao** [Meti0X7CB/SystemFetch#2]
The memory and CPU usage are different from those shown in the task m
![QQ图片20230927131743](https://github.com/Meti0X7CB/SystemFetch/assets/21172863/26e717ee-d5af-46cc-b23c-3506ba423c2d)
anager.

**Comment by Meti0X7CB** [comment]
The way windows task manager shows the percentage is different from what they provide via their API. Not much can be done till they implement a way to calculate the cores properly. This is a known issue especially in newer CPUs with efficiency cores that get counted incorrectly.
For the RAM windows task manager shows "committed" memory in use separately from "compressed". Using windows API you can't get the "compressed" amount which is shown in task manager. 
As an example:
<img width="561" alt="image" src="https://github.com/Meti0X7CB/SystemFetch/assets/8690114/82eec8ae-fd65-466e-b008-f9ee2c6f9ecb">
here 8.1 is "in use" or aka "compressed" and it is whats shown in the overview. However 12.2 is "committed" meaning its reserved. This is same thing as swap memory in Linux OS. 
Now Microsoft API returns the "committed" memory but they show "compressed" in overview. 

Hope that clears the doubts about usage not matching Windows Task Manager.

I will close this for now, till there is an updated method to calculate the new efficiency cores on newer CPUs.

**Comment by Meti0X7CB** [comment]
BTW, I've reworked the system calculation now so it would be very close to what you see in Windows Task Manager.
