### ISSUE TITLE
Possible game stats (Ping, ...)

### ISSUE THREAD

**Issue by XPSYDEUS** [Meti0X7CB/SystemFetch#3]
can you please add one for ping
it would be so amazing if it's a small side bar that expend on hover
like if am in a game I can see the ping only, on hover it shows the rest of the stats that would be cool

**Comment by Meti0X7CB** [comment]
sounds like a cool idea. I'll look into it for next release

**Comment by Meti0X7CB** [comment]
Please find the new widget GameFetch [here](https://github.com/Meti0X7CB/GameFetch)
